'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ApiError, interpretReading } from '@/lib/api';
import { MarkdownProse } from '@/lib/markdown';
import type { Interpretation } from '@/lib/types';

interface InterpretationPanelProps {
  readingId: number;
  locale: 'ru' | 'en';
  initial: Interpretation | null;
}

const labels = {
  ru: {
    cta: 'Раскрыть значение',
    loading: 'Карты складываются в историю...',
    error: 'Что-то пошло не так. Попробуй ещё раз.',
    payRequired: 'Нужна Premium-подписка или кредиты, чтобы продолжить.',
    pricing: 'Открыть тарифы',
    footnote: 'Интерпретация сгенерирована AI. Это не предсказание — это зеркало.',
    retry: 'Попробовать снова',
  },
  en: {
    cta: 'Reveal the reading',
    loading: 'The cards are weaving a story...',
    error: 'Something went wrong. Try again.',
    payRequired: 'Premium subscription or credits are needed to continue.',
    pricing: 'Open pricing',
    footnote: 'Interpretation generated by AI. Not a prediction — a mirror.',
    retry: 'Try again',
  },
} as const;

export default function InterpretationPanel({ readingId, locale, initial }: InterpretationPanelProps) {
  const t = labels[locale];
  const [interpretation, setInterpretation] = useState<Interpretation | null>(initial);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<'generic' | 'payment' | null>(null);

  const fetchInterpretation = async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await interpretReading(readingId);
      setInterpretation(result);
    } catch (e) {
      if (e instanceof ApiError && e.status === 402) {
        setError('payment');
      } else {
        setError('generic');
      }
    } finally {
      setLoading(false);
    }
  };

  if (interpretation) {
    return (
      <motion.section
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="w-full max-w-2xl mx-auto mt-12"
      >
        <div className="flex items-center gap-4 mb-6" aria-hidden>
          <div className="flex-1 h-px" style={{ background: 'rgba(212,175,55,0.2)' }} />
          <span style={{ color: 'rgba(212,175,55,0.6)', fontSize: '0.75rem', letterSpacing: '0.3em' }}>
            ✦
          </span>
          <div className="flex-1 h-px" style={{ background: 'rgba(212,175,55,0.2)' }} />
        </div>
        <MarkdownProse
          body={interpretation.body_md}
          className="font-serif text-[15px] md:text-base"
        />
        <p
          className="mt-8 text-[10px] tracking-widest uppercase opacity-50"
          style={{ color: 'rgba(201,194,224,0.5)', letterSpacing: '0.18em' }}
        >
          {t.footnote}
        </p>
      </motion.section>
    );
  }

  return (
    <section className="w-full max-w-2xl mx-auto mt-12 flex flex-col items-center">
      <AnimatePresence mode="wait">
        {loading ? (
          <motion.p
            key="loading"
            initial={{ opacity: 0 }}
            animate={{ opacity: [0.4, 1, 0.4] }}
            exit={{ opacity: 0 }}
            transition={{ duration: 1.5, repeat: Infinity, ease: 'easeInOut' }}
            className="font-serif italic"
            style={{ color: 'rgba(212,175,55,0.75)' }}
          >
            {t.loading}
          </motion.p>
        ) : error === 'payment' ? (
          <motion.div
            key="payment"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="flex flex-col items-center gap-4"
          >
            <p className="font-serif text-sm" style={{ color: 'rgba(201,194,224,0.75)' }}>
              {t.payRequired}
            </p>
            <a
              href="/pricing"
              className="px-6 py-2.5 rounded-full text-xs tracking-widest uppercase"
              style={{
                background: 'linear-gradient(135deg, rgba(212,175,55,0.2), rgba(212,175,55,0.05))',
                border: '1px solid #d4af37',
                color: '#d4af37',
                letterSpacing: '0.18em',
              }}
            >
              {t.pricing}
            </a>
          </motion.div>
        ) : error === 'generic' ? (
          <motion.div
            key="error"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="flex flex-col items-center gap-3"
          >
            <p className="font-serif text-sm" style={{ color: 'rgba(201,194,224,0.6)' }}>
              {t.error}
            </p>
            <button
              onClick={fetchInterpretation}
              className="px-6 py-2 rounded-full text-xs tracking-widest uppercase"
              style={{
                border: '1px solid rgba(212,175,55,0.4)',
                color: 'rgba(212,175,55,0.85)',
                letterSpacing: '0.12em',
              }}
            >
              {t.retry}
            </button>
          </motion.div>
        ) : (
          <motion.button
            key="cta"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            whileHover={{ scale: 1.03 }}
            whileTap={{ scale: 0.97 }}
            onClick={fetchInterpretation}
            className="px-8 py-3 rounded-full text-xs tracking-widest uppercase"
            style={{
              background: 'linear-gradient(135deg, rgba(212,175,55,0.25), rgba(212,175,55,0.05))',
              border: '1px solid #d4af37',
              color: '#d4af37',
              letterSpacing: '0.22em',
              boxShadow: '0 0 24px rgba(212,175,55,0.15)',
            }}
          >
            ✦ {t.cta}
          </motion.button>
        )}
      </AnimatePresence>
    </section>
  );
}
