'use client';

import { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ApiError, interpretReading } from '@/lib/api';
import { MarkdownProse } from '@/lib/markdown';
import type { Interpretation } from '@/lib/types';

interface InterpretationPanelProps {
  readingId: number;
  locale: 'ru' | 'en';
  initial: Interpretation | null;
}

const labels = {
  ru: {
    placeholder: 'О чём ты думаешь? Расскажи свою историю, задай вопрос — карты ответят через призму твоих слов…',
    cta: 'Раскрыть значение',
    loading: 'Карты складываются в историю…',
    error: 'Что-то пошло не так. Попробуй ещё раз.',
    payRequired: 'Нужна Premium-подписка или кредиты, чтобы продолжить.',
    rateLimited: 'Ты использовал 3 бесплатных интерпретации сегодня. Войди или зарегистрируйся — это бесплатно.',
    login: 'Войти',
    pricing: 'Открыть тарифы',
    footnote: 'Интерпретация сгенерирована AI. Это не предсказание — это зеркало.',
    retry: 'Попробовать снова',
    hint: 'Чем конкретнее вопрос, тем точнее ответ',
  },
  en: {
    placeholder: "What's on your mind? Share your story, ask a question — the cards will answer through the lens of your words…",
    cta: 'Reveal the reading',
    loading: 'The cards are weaving a story…',
    error: 'Something went wrong. Try again.',
    payRequired: 'Premium subscription or credits are needed to continue.',
    rateLimited: "You've used 3 free interpretations today. Log in or sign up — it's free.",
    login: 'Log in',
    pricing: 'Open pricing',
    footnote: 'Interpretation generated by AI. Not a prediction — a mirror.',
    retry: 'Try again',
    hint: 'The more specific the question, the sharper the answer',
  },
} as const;

export default function InterpretationPanel({ readingId, locale, initial }: InterpretationPanelProps) {
  const t = labels[locale];
  const [interpretation, setInterpretation] = useState<Interpretation | null>(initial);
  const [question, setQuestion] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<'generic' | 'payment' | 'rate_limit' | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Auto-resize textarea
  useEffect(() => {
    const el = textareaRef.current;
    if (el) {
      el.style.height = 'auto';
      el.style.height = `${Math.min(el.scrollHeight, 200)}px`;
    }
  }, [question]);

  const fetchInterpretation = async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await interpretReading(readingId, question);
      setInterpretation(result);
    } catch (e) {
      if (e instanceof ApiError && e.status === 402) {
        setError('payment');
      } else if (e instanceof ApiError && e.status === 429) {
        setError('rate_limit');
      } else {
        setError('generic');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && (e.ctrlKey || e.metaKey) && !loading) {
      e.preventDefault();
      void fetchInterpretation();
    }
  };

  // Already have an interpretation — show it
  if (interpretation) {
    return (
      <motion.section
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="w-full max-w-2xl mx-auto mt-12"
      >
        <div className="flex items-center gap-4 mb-6" aria-hidden>
          <div className="flex-1 h-px" style={{ background: 'rgba(212,175,55,0.2)' }} />
          <span style={{ color: 'rgba(212,175,55,0.6)', fontSize: '0.75rem', letterSpacing: '0.3em' }}>
            ✦
          </span>
          <div className="flex-1 h-px" style={{ background: 'rgba(212,175,55,0.2)' }} />
        </div>
        <MarkdownProse
          body={interpretation.body_md}
          className="font-serif text-[15px] md:text-base"
        />
        <p
          className="mt-8 text-[10px] tracking-widest uppercase opacity-50"
          style={{ color: 'rgba(201,194,224,0.5)', letterSpacing: '0.18em' }}
        >
          {t.footnote}
        </p>
      </motion.section>
    );
  }

  // Input form
  return (
    <section className="w-full max-w-2xl mx-auto mt-12 flex flex-col items-center">
      <AnimatePresence mode="wait">
        {loading ? (
          <motion.div
            key="loading"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="flex flex-col items-center gap-4 w-full"
          >
            <motion.p
              className="font-serif italic"
              style={{ color: 'rgba(212,175,55,0.75)' }}
              animate={{ opacity: [0.4, 1, 0.4] }}
              transition={{ duration: 1.5, repeat: Infinity, ease: 'easeInOut' }}
            >
              {t.loading}
            </motion.p>
            {question && (
              <p
                className="font-serif text-sm italic text-center max-w-md"
                style={{ color: 'rgba(201,194,224,0.4)' }}
              >
                &laquo;{question}&raquo;
              </p>
            )}
          </motion.div>
        ) : error === 'rate_limit' ? (
          <motion.div
            key="rate_limit"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="flex flex-col items-center gap-4 text-center"
          >
            <p className="font-serif text-sm" style={{ color: 'rgba(201,194,224,0.75)' }}>
              {t.rateLimited}
            </p>
            <a
              href="/login"
              className="px-6 py-2.5 rounded-full text-xs tracking-widest uppercase"
              style={{
                background: 'linear-gradient(135deg, rgba(212,175,55,0.25), rgba(212,175,55,0.05))',
                border: '1px solid #d4af37',
                color: '#d4af37',
                letterSpacing: '0.18em',
              }}
            >
              ✦ {t.login}
            </a>
          </motion.div>
        ) : error === 'payment' ? (
          <motion.div
            key="payment"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="flex flex-col items-center gap-4"
          >
            <p className="font-serif text-sm" style={{ color: 'rgba(201,194,224,0.75)' }}>
              {t.payRequired}
            </p>
            <a
              href="/pricing"
              className="px-6 py-2.5 rounded-full text-xs tracking-widest uppercase"
              style={{
                background: 'linear-gradient(135deg, rgba(212,175,55,0.2), rgba(212,175,55,0.05))',
                border: '1px solid #d4af37',
                color: '#d4af37',
                letterSpacing: '0.18em',
              }}
            >
              {t.pricing}
            </a>
          </motion.div>
        ) : error === 'generic' ? (
          <motion.div
            key="error"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="flex flex-col items-center gap-3"
          >
            <p className="font-serif text-sm" style={{ color: 'rgba(201,194,224,0.6)' }}>
              {t.error}
            </p>
            <button
              onClick={fetchInterpretation}
              className="px-6 py-2 rounded-full text-xs tracking-widest uppercase"
              style={{
                border: '1px solid rgba(212,175,55,0.4)',
                color: 'rgba(212,175,55,0.85)',
                letterSpacing: '0.12em',
              }}
            >
              {t.retry}
            </button>
          </motion.div>
        ) : (
          <motion.div
            key="form"
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="w-full flex flex-col items-center gap-5"
          >
            <div className="w-full relative">
              <textarea
                ref={textareaRef}
                value={question}
                onChange={(e) => setQuestion(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder={t.placeholder}
                rows={3}
                maxLength={1000}
                className="w-full resize-none rounded-xl px-5 py-4 font-serif text-sm md:text-base leading-relaxed outline-none transition-all placeholder:italic"
                style={{
                  background: 'rgba(28,24,64,0.5)',
                  border: '1px solid rgba(212,175,55,0.25)',
                  color: 'rgba(201,194,224,0.9)',
                  minHeight: '80px',
                  maxHeight: '200px',
                }}
                onFocus={(e) => {
                  e.currentTarget.style.borderColor = 'rgba(212,175,55,0.5)';
                  e.currentTarget.style.boxShadow = '0 0 20px rgba(212,175,55,0.08)';
                }}
                onBlur={(e) => {
                  e.currentTarget.style.borderColor = 'rgba(212,175,55,0.25)';
                  e.currentTarget.style.boxShadow = 'none';
                }}
              />
              {question.length > 0 && (
                <span
                  className="absolute bottom-2 right-3 text-[10px]"
                  style={{ color: 'rgba(201,194,224,0.3)' }}
                >
                  {question.length}/1000
                </span>
              )}
            </div>

            <p
              className="text-[11px] tracking-wide"
              style={{ color: 'rgba(201,194,224,0.35)', letterSpacing: '0.05em' }}
            >
              {t.hint}
            </p>

            <div className="flex flex-col sm:flex-row items-center gap-3">
              <motion.button
                whileHover={{ scale: 1.03 }}
                whileTap={{ scale: 0.97 }}
                onClick={fetchInterpretation}
                disabled={!question.trim()}
                className="px-8 py-3 rounded-full text-xs tracking-widest uppercase transition-opacity"
                style={{
                  background: question.trim()
                    ? 'linear-gradient(135deg, rgba(212,175,55,0.25), rgba(212,175,55,0.05))'
                    : 'rgba(201,194,224,0.05)',
                  border: `1px solid ${question.trim() ? '#d4af37' : 'rgba(201,194,224,0.15)'}`,
                  color: question.trim() ? '#d4af37' : 'rgba(201,194,224,0.35)',
                  letterSpacing: '0.22em',
                  boxShadow: question.trim() ? '0 0 24px rgba(212,175,55,0.15)' : 'none',
                  cursor: question.trim() ? 'pointer' : 'default',
                }}
              >
                ✦ {t.cta}
              </motion.button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  );
}
