# Generated by Django 5.0.6 on 2026-05-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='card',
            new_name='tarot_card_suit_8a84db_idx',
            old_name='tarot_card_suit_number_idx',
        ),
    ]
