# Generated by Django 5.0.6 on 2026-09-21 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0002_rename_tarot_card_suit_number_idx_tarot_card_suit_8a84db_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RitualDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ritual_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-day'], name='tarot_ritua_user_id_84947c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ritualday',
            constraint=models.UniqueConstraint(fields=('user', 'day'), name='ritual_day_once'),
        ),
    ]
