# Generated by Django 5.0.6 on 2026-05-28 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NatalInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_md', models.TextField()),
                ('model_used', models.CharField(max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='NatalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_name', models.CharField(blank=True, max_length=128)),
                ('birth_date', models.DateField()),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_city', models.CharField(max_length=128)),
                ('birth_lat', models.FloatField()),
                ('birth_lng', models.FloatField()),
                ('birth_tz', models.CharField(max_length=64)),
                ('locale', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=8)),
                ('planets', models.JSONField()),
                ('houses', models.JSONField(default=list)),
                ('aspects', models.JSONField(default=list)),
                ('ascendant', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='natal_charts', to=settings.AUTH_USER_MODEL)),
                ('interpretation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart', to='natal.natalinterpretation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='natal_natal_user_id_4df6e4_idx')],
            },
        ),
    ]
