# Generated by Django 5.0.6 on 2026-05-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_email_6f2530_idx',
            old_name='users_user_email_idx',
        ),
    ]
