# Generated by Django 5.0.6 on 2026-05-28 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumerologyInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_md', models.TextField()),
                ('model_used', models.CharField(max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumerologyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('birth_date', models.DateField()),
                ('locale', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=8)),
                ('life_path', models.PositiveSmallIntegerField()),
                ('destiny', models.PositiveSmallIntegerField()),
                ('soul_urge', models.PositiveSmallIntegerField()),
                ('personality', models.PositiveSmallIntegerField()),
                ('birthday', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interpretation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading', to='numerology.numerologyinterpretation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numerology_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='numerology__user_id_171e80_idx')],
            },
        ),
    ]
