# Generated by Django 5.0.6 on 2026-05-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_tg_stars_subscription_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usageledger',
            name='kind',
            field=models.CharField(choices=[('ai_tarot', 'AI tarot reading'), ('ai_runes', 'AI rune cast'), ('ai_natal', 'AI natal chart'), ('ai_deep', 'AI deep reading'), ('grant_subscription', 'Subscription monthly grant'), ('grant_pack', 'Credit pack purchase')], max_length=24),
        ),
    ]
