# Generated by Django 5.0.6 on 2026-05-26 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('aett', models.PositiveSmallIntegerField()),
                ('symbol', models.CharField(max_length=4)),
                ('name_ru', models.CharField(max_length=64)),
                ('name_en', models.CharField(max_length=64)),
                ('meaning_ru', models.TextField()),
                ('meaning_en', models.TextField()),
                ('keywords_ru', models.JSONField(default=list)),
                ('keywords_en', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='RuneCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(choices=[('single', 'Single rune'), ('three', 'Three runes'), ('five', 'Five runes (cross)')], default='three', max_length=8)),
                ('question', models.TextField()),
                ('locale', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rune_casts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuneCastItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_index', models.PositiveSmallIntegerField()),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='runes.runecast')),
                ('rune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runes.rune')),
            ],
            options={
                'ordering': ['position_index'],
            },
        ),
        migrations.CreateModel(
            name='RuneInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_md', models.TextField()),
                ('model_used', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=32)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('cast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interpretation', to='runes.runecast')),
            ],
        ),
        migrations.AddIndex(
            model_name='runecast',
            index=models.Index(fields=['-created_at'], name='runes_runec_created_b9b4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='runecast',
            index=models.Index(fields=['user', '-created_at'], name='runes_runec_user_id_3cb68c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='runecastitem',
            unique_together={('cast', 'position_index')},
        ),
    ]
