# Generated by Django 5.0.6 on 2026-05-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reading',
            new_name='readings_re_created_c1b04c_idx',
            old_name='readings_reading_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='reading',
            new_name='readings_re_user_id_1105d9_idx',
            old_name='readings_reading_user_created_idx',
        ),
    ]
