# Generated by Django 5.0.6 on 2026-09-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_rename_readings_reading_created_at_idx_readings_re_created_c1b04c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingcard',
            name='x',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='readingcard',
            name='y',
            field=models.FloatField(default=0.5),
        ),
    ]
