# Generated by Django 5.0.6 on 2026-06-10 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_bot', '0006_telegramuser_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('channel', models.CharField(help_text='@username канала, например @tarro_bot_group', max_length=64)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('prize_count', models.PositiveSmallIntegerField(default=10)),
                ('prize_months', models.PositiveSmallIntegerField(default=1)),
                ('prize_plan_slug', models.CharField(default='premium', help_text='Slug плана из billing.Plan, который выдаём победителям.', max_length=64)),
                ('min_invites', models.PositiveSmallIntegerField(default=3, help_text='Минимум приглашённых, чтобы попасть в жеребьёвку.')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('finished', 'Завершён')], default='draft', max_length=16)),
                ('winners_drawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Конкурс',
                'verbose_name_plural': 'Конкурсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_link_url', models.URLField(max_length=255)),
                ('invite_link_name', models.CharField(max_length=32, unique=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('prize_granted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='contest.contest')),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to='telegram_bot.telegramuser')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_tg_id', models.BigIntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('still_member', models.BooleanField(default=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='contest.contestentry')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
            },
        ),
        migrations.AddConstraint(
            model_name='contestentry',
            constraint=models.UniqueConstraint(fields=('contest', 'tg_user'), name='uniq_contest_entry_per_user'),
        ),
        migrations.AddIndex(
            model_name='contestinvite',
            index=models.Index(fields=['invited_tg_id'], name='contest_con_invited_be6381_idx'),
        ),
        migrations.AddConstraint(
            model_name='contestinvite',
            constraint=models.UniqueConstraint(fields=('entry', 'invited_tg_id'), name='uniq_invite_per_invited_per_entry'),
        ),
    ]
