# Generated by Django 5.0.6 on 2026-06-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_telegramuser_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
