# Generated by Django 5.0.6 on 2026-09-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_telegramuser_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fact', 'Интересный факт'), ('promo', 'Промо бота')], default='fact', max_length=16)),
                ('topic', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('failed', 'Ошибка отправки')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tg_message_id', models.BigIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=64)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='telegram_bo_created_e502c8_idx'), models.Index(fields=['kind', '-created_at'], name='telegram_bo_kind_6291d7_idx')],
            },
        ),
    ]
