# Generated by Django 5.0.6 on 2026-05-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoroscopeAIReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=16)),
                ('date', models.DateField()),
                ('locale', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=8)),
                ('body_md', models.TextField()),
                ('model_used', models.CharField(max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['sign', 'date', 'locale'], name='horoscope_h_sign_c897e5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='horoscopeaireading',
            constraint=models.UniqueConstraint(fields=('sign', 'date', 'locale'), name='uniq_horoscope_sign_date_locale'),
        ),
    ]
