'use client';

import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useLocale } from 'next-intl';
import NatalWheel from '@/components/natal/NatalWheel';
import BigThree from '@/components/natal/BigThree';
import { MarkdownProse } from '@/lib/markdown';
import { ApiError, createNatalChart, interpretNatalChart, getBillingMe } from '@/lib/api';
import { getAccessToken } from '@/lib/auth';
import type { NatalChart, NatalInterpretation } from '@/lib/types';

// ---- Copy ----

const COPY = {
  ru: {
    title: 'Натальная карта',
    subtitle: 'Карта звёздного неба в момент вашего рождения',
    name_label: 'Имя (необязательно)',
    date_label: 'Дата рождения',
    time_label: 'Время рождения',
    time_hint: 'необязательно — нужно для домов и асцендента',
    city_label: 'Город рождения',
    city_placeholder: 'Москва, Нью-Йорк, Париж...',
    calculate: 'Рассчитать карту',
    calculating: 'Рассчитываю...',
    new_chart: 'Новая карта',
    interpret_cta: 'Раскрыть интерпретацию',
    interpreting: 'Читаю карту...',
    interpret_footnote: 'Интерпретация сгенерирована AI. Это не предсказание — это карта вашего потенциала.',
    premium_cta: 'Premium открывает все планеты, дома и AI-интерпретацию',
    planets_section: 'Планеты',
    free_planets_hint: 'Все планеты доступны в Premium',
    error_city: 'Город не найден. Проверьте написание.',
    error_generic: 'Ошибка. Попробуйте ещё раз.',
    interpret_error: 'Что-то пошло не так. Попробуйте ещё раз.',
    interpret_pay_required: 'AI-интерпретация доступна по Premium-подписке.',
    interpret_pricing: 'Открыть тарифы',
    retrograde: 'ретроградный',
    house: 'дом',
  },
  en: {
    title: 'Natal Chart',
    subtitle: 'A map of the sky at the moment of your birth',
    name_label: 'Name (optional)',
    date_label: 'Birth date',
    time_label: 'Birth time',
    time_hint: 'optional — needed for houses & ascendant',
    city_label: 'Birth city',
    city_placeholder: 'Moscow, New York, Paris...',
    calculate: 'Calculate chart',
    calculating: 'Calculating...',
    new_chart: 'New chart',
    interpret_cta: 'Reveal interpretation',
    interpreting: 'Reading the chart...',
    interpret_footnote: 'Interpretation generated by AI. Not a prediction — a map of your potential.',
    premium_cta: 'Premium unlocks all planets, houses, and AI interpretation',
    planets_section: 'Planets',
    free_planets_hint: 'All planets available with Premium',
    error_city: 'City not found. Check the spelling.',
    error_generic: 'Something went wrong. Please try again.',
    interpret_error: 'Something went wrong. Please try again.',
    interpret_pay_required: 'AI interpretation is available with a Premium subscription.',
    interpret_pricing: 'Open pricing',
    retrograde: 'retrograde',
    house: 'house',
  },
} as const;

// Planet display names
const PLANET_NAMES: Record<string, { ru: string; en: string }> = {
  Sun: { ru: 'Солнце', en: 'Sun' },
  Moon: { ru: 'Луна', en: 'Moon' },
  Mercury: { ru: 'Меркурий', en: 'Mercury' },
  Venus: { ru: 'Венера', en: 'Venus' },
  Mars: { ru: 'Марс', en: 'Mars' },
  Jupiter: { ru: 'Юпитер', en: 'Jupiter' },
  Saturn: { ru: 'Сатурн', en: 'Saturn' },
  Uranus: { ru: 'Уран', en: 'Uranus' },
  Neptune: { ru: 'Нептун', en: 'Neptune' },
  'North Node': { ru: 'Северный узел', en: 'North Node' },
};

// ---- Input field helper ----

function Field({
  label,
  hint,
  children,
}: {
  label: string;
  hint?: string;
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col gap-1.5">
      <label
        className="text-xs tracking-widest uppercase"
        style={{ color: 'rgba(201,194,224,0.6)', letterSpacing: '0.14em' }}
      >
        {label}
      </label>
      {hint && (
        <span className="text-[10px] italic" style={{ color: 'rgba(201,194,224,0.35)' }}>
          {hint}
        </span>
      )}
      {children}
    </div>
  );
}

const inputStyle: React.CSSProperties = {
  background: 'rgba(11,11,31,0.6)',
  border: '1px solid rgba(212,175,55,0.2)',
  color: 'rgba(201,194,224,0.95)',
  borderRadius: '12px',
  padding: '10px 14px',
  fontSize: '14px',
  outline: 'none',
  width: '100%',
  transition: 'border-color 0.2s',
};

// ---- Interpretation panel ----

function NatalInterpretationBlock({
  chartId,
  initial,
  isPremium,
  locale,
}: {
  chartId: number;
  initial: NatalInterpretation | null;
  isPremium: boolean;
  locale: 'ru' | 'en';
}) {
  const t = COPY[locale];
  const [interp, setInterp] = useState<NatalInterpretation | null>(initial);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<'generic' | 'payment' | null>(null);

  const handleInterpret = async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await interpretNatalChart(chartId);
      setInterp(result);
    } catch (e) {
      if (e instanceof ApiError && e.status === 402) {
        setError('payment');
      } else {
        setError('generic');
      }
    } finally {
      setLoading(false);
    }
  };

  if (interp) {
    return (
      <motion.section
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="w-full max-w-2xl mx-auto mt-10"
      >
        <div className="flex items-center gap-4 mb-6" aria-hidden>
          <div className="flex-1 h-px" style={{ background: 'rgba(212,175,55,0.2)' }} />
          <span style={{ color: 'rgba(212,175,55,0.6)', fontSize: '0.75rem' }}>✦</span>
          <div className="flex-1 h-px" style={{ background: 'rgba(212,175,55,0.2)' }} />
        </div>
        <MarkdownProse
          body={interp.body_md}
          className="font-serif text-[15px] md:text-base"
        />
        <p
          className="mt-8 text-[10px] tracking-widest uppercase opacity-50"
          style={{ color: 'rgba(201,194,224,0.5)', letterSpacing: '0.18em' }}
        >
          {t.interpret_footnote}
        </p>
      </motion.section>
    );
  }

  if (!isPremium) {
    return (
      <div
        className="w-full max-w-2xl mx-auto mt-8 rounded-2xl px-6 py-6 text-center"
        style={{
          background: 'linear-gradient(180deg, rgba(28,24,64,0.5), rgba(11,11,31,0.5))',
          border: '1px solid rgba(212,175,55,0.2)',
        }}
      >
        <p className="font-serif text-sm mb-4" style={{ color: 'rgba(201,194,224,0.7)' }}>
          {t.interpret_pay_required}
        </p>
        <a
          href="/pricing"
          className="px-6 py-2.5 rounded-full text-xs tracking-widest uppercase inline-block"
          style={{
            background: 'linear-gradient(135deg, rgba(212,175,55,0.2), rgba(212,175,55,0.05))',
            border: '1px solid #d4af37',
            color: '#d4af37',
            letterSpacing: '0.18em',
          }}
        >
          {t.interpret_pricing}
        </a>
      </div>
    );
  }

  return (
    <div className="flex flex-col items-center mt-8 gap-4">
      {error === 'payment' && (
        <p className="font-serif text-sm" style={{ color: 'rgba(201,194,224,0.7)' }}>
          {t.interpret_pay_required}
        </p>
      )}
      {error === 'generic' && (
        <p className="font-serif text-sm" style={{ color: 'rgba(201,194,224,0.7)' }}>
          {t.interpret_error}
        </p>
      )}
      {loading ? (
        <motion.p
          className="font-serif italic"
          style={{ color: 'rgba(212,175,55,0.75)' }}
          animate={{ opacity: [0.4, 1, 0.4] }}
          transition={{ duration: 1.5, repeat: Infinity, ease: 'easeInOut' }}
        >
          {t.interpreting}
        </motion.p>
      ) : (
        <motion.button
          whileHover={{ scale: 1.03 }}
          whileTap={{ scale: 0.97 }}
          onClick={() => void handleInterpret()}
          className="px-8 py-3 rounded-full text-xs tracking-widest uppercase"
          style={{
            background: 'linear-gradient(135deg, rgba(212,175,55,0.25), rgba(212,175,55,0.05))',
            border: '1px solid #d4af37',
            color: '#d4af37',
            letterSpacing: '0.22em',
            boxShadow: '0 0 24px rgba(212,175,55,0.15)',
          }}
        >
          ✦ {t.interpret_cta}
        </motion.button>
      )}
    </div>
  );
}

// ---- Planet list ----

function PlanetList({
  planets,
  isPremium,
  locale,
}: {
  planets: NatalChart['planets'];
  isPremium: boolean;
  locale: 'ru' | 'en';
}) {
  const t = COPY[locale];
  const BIG_THREE = new Set(['Sun', 'Moon']);

  const visible = isPremium ? planets : planets.filter((p) => BIG_THREE.has(p.name));

  return (
    <div className="w-full max-w-2xl mx-auto mt-8">
      <div
        className="text-[10px] tracking-widest uppercase mb-4"
        style={{ color: 'rgba(212,175,55,0.55)', letterSpacing: '0.2em' }}
      >
        {t.planets_section}
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
        {visible.map((planet) => {
          const name = PLANET_NAMES[planet.name]?.[locale] ?? planet.name;
          return (
            <div
              key={planet.name}
              className="flex items-center gap-3 rounded-xl px-4 py-2.5"
              style={{
                background: 'rgba(28,24,64,0.4)',
                border: '1px solid rgba(212,175,55,0.1)',
              }}
            >
              <span style={{ color: '#d4af37', fontSize: '16px', minWidth: '20px', textAlign: 'center' }}>
                {planet.glyph}
              </span>
              <div className="flex flex-col min-w-0">
                <span className="text-xs" style={{ color: 'rgba(201,194,224,0.85)' }}>
                  {name}
                  {planet.retrograde && (
                    <span className="ml-1 text-[10px]" style={{ color: 'rgba(201,194,224,0.45)' }}>
                      ℞ {t.retrograde}
                    </span>
                  )}
                </span>
                <span className="text-[11px]" style={{ color: 'rgba(201,194,224,0.5)' }}>
                  {planet.emoji} {planet.sign} {planet.position.toFixed(1)}°
                  {planet.house > 0 && ` · ${planet.house} ${t.house}`}
                </span>
              </div>
            </div>
          );
        })}
      </div>
      {!isPremium && (
        <p
          className="text-xs mt-3 text-center font-serif italic"
          style={{ color: 'rgba(201,194,224,0.35)' }}
        >
          {t.free_planets_hint}
        </p>
      )}
    </div>
  );
}

// ---- Main page ----

export default function NatalPage() {
  const locale = useLocale() as 'ru' | 'en';
  const t = COPY[locale];

  // Form state
  const [birthName, setBirthName] = useState('');
  const [birthDate, setBirthDate] = useState('');
  const [birthTime, setBirthTime] = useState('');
  const [birthCity, setBirthCity] = useState('');

  // App state
  const [chart, setChart] = useState<NatalChart | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<'city' | 'generic' | null>(null);
  const [isPremium, setIsPremium] = useState(false);
  const resultRef = useRef<HTMLDivElement>(null);

  // Detect premium
  useEffect(() => {
    if (!getAccessToken()) return;
    getBillingMe()
      .then((me) => {
        setIsPremium(me.tier !== 'free');
      })
      .catch(() => {/* silently ignore */});
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!birthDate || !birthCity.trim()) return;

    setLoading(true);
    setError(null);

    try {
      const result = await createNatalChart({
        birth_name: birthName.trim(),
        birth_date: birthDate,
        birth_time: birthTime || undefined,
        birth_city: birthCity.trim(),
        locale,
      });
      setChart(result);
      // Scroll to result after a frame
      setTimeout(() => {
        resultRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }, 100);
    } catch (e) {
      if (e instanceof ApiError) {
        const payload = e.payload as Record<string, unknown> | null;
        if (
          e.status === 400 &&
          payload &&
          typeof payload === 'object' &&
          ('birth_city' in payload || 'geocode' in payload)
        ) {
          setError('city');
        } else {
          setError('generic');
        }
      } else {
        setError('generic');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setChart(null);
    setError(null);
  };

  return (
    <main
      className="min-h-screen px-4 py-12 md:py-16 pb-24"
      style={{ background: 'radial-gradient(ellipse at 50% 0%, rgba(28,24,64,0.8) 0%, #0b0b1f 60%)' }}
    >
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <motion.header
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-10"
        >
          <h1
            className="font-serif text-3xl md:text-4xl mb-3"
            style={{ color: '#d4af37', letterSpacing: '0.08em', textShadow: '0 0 40px rgba(212,175,55,0.2)' }}
          >
            ✦ {t.title}
          </h1>
          <p
            className="font-serif text-sm md:text-base italic max-w-xl mx-auto"
            style={{ color: 'rgba(201,194,224,0.7)' }}
          >
            {t.subtitle}
          </p>
        </motion.header>

        <AnimatePresence mode="wait">
          {/* ---- Form ---- */}
          {!chart && (
            <motion.form
              key="form"
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -12 }}
              transition={{ duration: 0.4 }}
              onSubmit={(e) => void handleSubmit(e)}
              className="flex flex-col gap-5 max-w-lg mx-auto"
            >
              {/* Name */}
              <Field label={t.name_label}>
                <input
                  type="text"
                  value={birthName}
                  onChange={(e) => setBirthName(e.target.value)}
                  placeholder="Анна / Anna"
                  style={inputStyle}
                  onFocus={(e) => { e.currentTarget.style.borderColor = 'rgba(212,175,55,0.5)'; }}
                  onBlur={(e) => { e.currentTarget.style.borderColor = 'rgba(212,175,55,0.2)'; }}
                />
              </Field>

              {/* Birth date */}
              <Field label={t.date_label}>
                <input
                  type="date"
                  value={birthDate}
                  onChange={(e) => setBirthDate(e.target.value)}
                  required
                  style={{ ...inputStyle, colorScheme: 'dark' }}
                  onFocus={(e) => { e.currentTarget.style.borderColor = 'rgba(212,175,55,0.5)'; }}
                  onBlur={(e) => { e.currentTarget.style.borderColor = 'rgba(212,175,55,0.2)'; }}
                />
              </Field>

              {/* Birth time */}
              <Field label={t.time_label} hint={t.time_hint}>
                <input
                  type="time"
                  value={birthTime}
                  onChange={(e) => setBirthTime(e.target.value)}
                  style={{ ...inputStyle, colorScheme: 'dark' }}
                  onFocus={(e) => { e.currentTarget.style.borderColor = 'rgba(212,175,55,0.5)'; }}
                  onBlur={(e) => { e.currentTarget.style.borderColor = 'rgba(212,175,55,0.2)'; }}
                />
              </Field>

              {/* Birth city */}
              <Field label={t.city_label}>
                <input
                  type="text"
                  value={birthCity}
                  onChange={(e) => setBirthCity(e.target.value)}
                  placeholder={t.city_placeholder}
                  required
                  style={inputStyle}
                  onFocus={(e) => { e.currentTarget.style.borderColor = 'rgba(212,175,55,0.5)'; }}
                  onBlur={(e) => { e.currentTarget.style.borderColor = 'rgba(212,175,55,0.2)'; }}
                />
              </Field>

              {/* Error messages */}
              {error && (
                <motion.p
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="text-sm text-center font-serif italic"
                  style={{ color: 'rgba(200,80,80,0.85)' }}
                >
                  {error === 'city' ? t.error_city : t.error_generic}
                </motion.p>
              )}

              {/* Submit */}
              <div className="flex justify-center mt-2">
                <motion.button
                  type="submit"
                  disabled={loading || !birthDate || !birthCity.trim()}
                  whileHover={!loading ? { scale: 1.03 } : undefined}
                  whileTap={!loading ? { scale: 0.97 } : undefined}
                  className="px-10 py-3 rounded-full text-xs tracking-widest uppercase"
                  style={{
                    background: birthDate && birthCity.trim()
                      ? 'linear-gradient(135deg, rgba(212,175,55,0.25), rgba(212,175,55,0.05))'
                      : 'rgba(201,194,224,0.05)',
                    border: `1px solid ${birthDate && birthCity.trim() ? '#d4af37' : 'rgba(201,194,224,0.15)'}`,
                    color: birthDate && birthCity.trim() ? '#d4af37' : 'rgba(201,194,224,0.35)',
                    letterSpacing: '0.22em',
                    boxShadow: birthDate && birthCity.trim() ? '0 0 24px rgba(212,175,55,0.15)' : 'none',
                    opacity: loading ? 0.6 : 1,
                    cursor: !loading && birthDate && birthCity.trim() ? 'pointer' : 'default',
                  }}
                >
                  {loading ? t.calculating : `✦ ${t.calculate}`}
                </motion.button>
              </div>
            </motion.form>
          )}

          {/* ---- Results ---- */}
          {chart && (
            <motion.div
              key="result"
              ref={resultRef}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.5 }}
              className="flex flex-col items-center gap-8"
            >
              {/* SVG Wheel */}
              <NatalWheel
                planets={chart.planets}
                houses={chart.houses}
                aspects={chart.aspects}
                ascendant={chart.ascendant}
                isPremium={isPremium}
                birthName={chart.birth_name || undefined}
                birthDate={chart.birth_date}
              />

              {/* Big 3 cards */}
              <div className="w-full max-w-2xl">
                <BigThree
                  planets={chart.planets}
                  ascendant={chart.ascendant}
                  isPremium={isPremium}
                  locale={locale}
                />
              </div>

              {/* Planet list */}
              <PlanetList
                planets={chart.planets}
                isPremium={isPremium}
                locale={locale}
              />

              {/* Interpretation */}
              <div className="w-full max-w-2xl">
                <NatalInterpretationBlock
                  chartId={chart.id}
                  initial={chart.interpretation}
                  isPremium={isPremium}
                  locale={locale}
                />
              </div>

              {/* New chart button */}
              <motion.button
                onClick={handleReset}
                whileHover={{ scale: 1.03 }}
                whileTap={{ scale: 0.97 }}
                className="mt-4 px-8 py-2.5 rounded-full text-xs tracking-widest uppercase"
                style={{
                  border: '1px solid rgba(212,175,55,0.3)',
                  color: 'rgba(212,175,55,0.7)',
                  letterSpacing: '0.18em',
                }}
              >
                ↺ {t.new_chart}
              </motion.button>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </main>
  );
}
